# Generated by Django 4.1 on 2024-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
