# Generated by Django 4.1 on 2024-10-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
